### PR TITLE
Fix 3 rx handling bugs; timeout, short read, out-of-sync

### PR DESCRIPTION
**Pull request by wutje**
When not plugging in the radio we expect to only see timeout errors. However due to timeout being checked AFTER the read() call the len parameter was updated and no longer was 0 returned.

If less then 4 was read (a short read) then uninitialized data was used, for length and/or magic check.

If the magic byte does not match then the  rx buffer should be flushed before trying again. Otherwise sync will probably never be achieved. This solves the bug where plugging in the radio show continues streams of magic packet errors. For me k5prog -Y -D now always works, while before it could fail.

### CODE REVIEW

**Comment by sq5bpf** [comment]
thanks. i will look at all pull requests end of december 2023

**Comment by wutje** [comment]
Any chance that you had a look at this?

**Comment by sq5bpf** [comment]
no, but will try to have some time today

**Comment by wutje** [comment]
No worries. Just checking.

**Comment by sq5bpf** [comment]
Hi, Thanks for your patch. The source seems correct, so i've merged it. 

Is there some way that i can cause a short read of the magic bytes? i've tried turning the radio on during k5prog waiting for the message multiple times, but wasn't able to get a read with len != 4

**Comment by wutje** [comment]
Sometimes when plugging in I get an extra spurious byte. And then we will no longer be in sync.

**Comment by sq5bpf** [comment]
In what OS?

**Comment by wutje** [comment]
> In what OS?

Debian stable

**Pull request merged**
